ci : Check run event for Kernel checker
As part of QLI 2.0 Kernel CI/CD below should be flow :
1. Dev raises PR
2. Kernel checker is triggered
3. If kernel checker is passed, and maintainer approves PR then,
   Kernel CI/CD i.e sync, build test should trigger
4. If kernel checker fails, developer should fix the issue and
   repush the PR which will trigger kernel checker again

To achieve this, post a check run event for kernel checker in pass case
for QLI 2.0 branch.
Based on check run event and approvals Kernel CI/CD will be triggered from
Coral

Signed-off-by: Salendarsingh Gaud <sgaud@qti.qualcomm.com>

diff --git a/.github/actions/check_run/action.yml b/.github/actions/check_run/action.yml
--- a/.github/actions/check_run/action.yml
+++ b/.github/actions/check_run/action.yml
@@ -20,7 +20,7 @@ inputs:
     required: true
   workflow_name:
     description: Workflow name to post check_run
-    required: false
+    required: true
 
 runs:
   using: "composite"
@@ -42,9 +42,24 @@ runs:
         ACCESS_TOKEN="${{ steps.app-token.outputs.token }}"
         s3_location="${{ inputs.s3_location }}"
         REPO="${{ inputs.repo }}"
-        post_name="Artifacts${{ inputs.workflow_name }} uploaded to S3"
+        workflow_name="${{ inputs.workflow_name }}"
 
-        echo "Creating check run for commit: $HEAD_SHA"
+        echo "Creating check run for workflow : $workflow_name and commit: $HEAD_SHA"
+
+        if [ "$workflow_name" = "pre_merge" ] || [ "$workflow_name" = "pre_merge_ubuntu" ] || [ "$workflow_name" = "pre_merge_yocto" ]; then
+          post_name="Artifacts for ${{ inputs.workflow_name }} uploaded to S3"
+          title="Check S3 Location"
+          text=$s3_location
+        elif [ "$workflow_name" = "Kernel Checkers" ]; then
+          post_name="Kernel Checkers passed"
+          echo "$post_name"
+          title="Kernel checker"
+          text=""
+        fi
+
+        echo "Post name : $post_name"
+        echo "Title : $title"
+
         CHECK_RUN_ID=$(curl -s -L -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer $ACCESS_TOKEN" \
@@ -55,16 +70,16 @@ runs:
             "head_sha": "'"$HEAD_SHA"'",
             "status": "in_progress",
             "output": {
-              "title": "Check S3 Location",
+              "title": "'"$title"'",
               "summary": "",
-              "text": "'"$s3_location"'"
+              "text": "'"$text"'"
             }
           }' | jq -r '.id')
 
-        if [ -z "$CHECK_RUN_ID" ]; then
-          echo "Failed to create check run. Exiting."
-          exit 1
-        fi
+          if [ -z "$CHECK_RUN_ID" ]; then
+            echo "Failed to create check run. Exiting."
+            exit 1
+          fi
 
         echo "Check run created with ID: $CHECK_RUN_ID"
 
@@ -80,10 +95,10 @@ runs:
             "status": "completed",
             "conclusion": "success",
             "output": {
-              "title": "Check S3 Location",
+              "title": "'"$title"'",
               "summary": "",
-              "text": "'"$s3_location"'"
+              "text": "'"$text"'"
             }
           }'
 
-        echo "Check run updated successfully."
+        echo "Check run updated successfully for $workflow_name"
